### ISSUE TITLE
Night time lighting during day?

### ISSUE THREAD

**Issue by Zadrave** [gri573/voxlementary#7]
For some reason during day time in ATM6 I get really dark lighting. However when I use Complementary shaders, it works just fine. Voxel lighting seems to work correctly though.

![2021-08-13_18 22 22](https://user-images.githubusercontent.com/88107721/129424036-bc6b6f82-b25b-452f-ba93-bb9e15ffb526.png)
![2021-08-13_18 23 13](https://user-images.githubusercontent.com/88107721/129424051-ef5c166c-aa7a-44dc-9348-f662e7a9b8b9.png)
![2021-08-13_18 22 26](https://user-images.githubusercontent.com/88107721/129424043-5ef3ceae-7a1e-4b52-baf6-aabaebcb116b.png)
![2021-08-13_18 23 11](https://user-images.githubusercontent.com/88107721/129424045-5e792aad-3429-4a1f-beb5-3195c4242a96.png)

I have tried resetting all the options to default and so on.

 - Optifine version: HD U G8
 - Minecraft version: 1.16.5
 - Mods: yes
 - Mac: no
 - GPU: RTX 2080

**Comment by tajemniktv** [comment]
Have you tried *fixes* available [here](https://justpaste.it/60cgu)?

**Comment by Zadrave** [comment]
I haves, yes. I have tweaked all the configs already for Complementary itself. Although wouldn't base Complementary not work if this didn't? That is what I find confusing.

**Comment by Zadrave** [comment]
Here's an F3

![](https://i.imgur.com/H07adZC.jpeg)

**Comment by tajemniktv** [comment]
Yeah, that's what I thought after posting this comment - And that's why I deleted it (I thought I did it fast enough so noone would notice xD)

But anyways - ATM6 is a pretty big modpack so it *might* be an incompatibility with some mod(s). You could try the "Thanos Method" or as I prefer to call it "50/50 Method" 
![image](https://user-images.githubusercontent.com/12156943/129427778-f2135ac3-a350-4e8b-8be6-c6788b067c24.png)
This way you will be able to tell which mod is causing the issue and disable it for the time of this issue being invesigated. 
(Remember to do this on seperate world!)

**Comment by gri573** [comment]
This is because Optifine doesn't pass all varyings (specifically lmCoord) in gbuffers_terrain correctly. I will investigate a workaround for the issue

**Comment by gri573** [comment]
this is described in more detail in #9, so I'm closing it
